// <auto-generated />
using System;
using AgriEnergyConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgriEnergyConnect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250515214842_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("AgriEnergyConnect.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            EmployeeNumber = 0,
                            FirstName = "admin",
                            LastName = "admin",
                            Password = "Admin",
                            Position = "Admin",
                            Username = "Admin"
                        },
                        new
                        {
                            EmployeeId = 2,
                            EmployeeNumber = 1,
                            FirstName = "employee",
                            LastName = "employee",
                            Password = "Employee",
                            Position = "Employee",
                            Username = "Employee"
                        },
                        new
                        {
                            EmployeeId = 3,
                            EmployeeNumber = 2002,
                            FirstName = "Karen",
                            LastName = "Johnson",
                            Password = "pass456",
                            Position = "Employee",
                            Username = "employee_karen"
                        },
                        new
                        {
                            EmployeeId = 4,
                            EmployeeNumber = 2003,
                            FirstName = "Steve",
                            LastName = "Wilson",
                            Password = "pass789",
                            Position = "Employee",
                            Username = "employee_steve"
                        },
                        new
                        {
                            EmployeeId = 5,
                            EmployeeNumber = 2004,
                            FirstName = "Linda",
                            LastName = "Martinez",
                            Password = "pass101",
                            Position = "Employee",
                            Username = "employee_linda"
                        },
                        new
                        {
                            EmployeeId = 6,
                            EmployeeNumber = 2005,
                            FirstName = "Mark",
                            LastName = "Brown",
                            Password = "pass202",
                            Position = "Employee",
                            Username = "employee_mark"
                        });
                });

            modelBuilder.Entity("AgriEnergyConnect.Models.Farmer", b =>
                {
                    b.Property<int>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeOfProduce")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FarmerId");

                    b.ToTable("Farmers");

                    b.HasData(
                        new
                        {
                            FarmerId = 1,
                            Address = "123 Farm Lane",
                            CompanyName = "Green Farms",
                            Email = "john@example.com",
                            FirstName = "farmer",
                            LastName = "farmer",
                            Password = "Farmer",
                            PhoneNumber = "555-1234",
                            TypeOfProduce = "Fruits",
                            Username = "Farmer"
                        },
                        new
                        {
                            FarmerId = 2,
                            Address = "456 Wheat Rd",
                            CompanyName = "Golden Fields",
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Password = "farmer2pass",
                            PhoneNumber = "555-5678",
                            TypeOfProduce = "Grains",
                            Username = "golden_fields"
                        },
                        new
                        {
                            FarmerId = 3,
                            Address = "789 Organic St",
                            CompanyName = "Sunrise Organics",
                            Email = "michael@example.com",
                            FirstName = "Michael",
                            LastName = "Thompson",
                            Password = "farmer3pass",
                            PhoneNumber = "555-7890",
                            TypeOfProduce = "Vegetables",
                            Username = "sunrise_organics"
                        },
                        new
                        {
                            FarmerId = 4,
                            Address = "321 Fresh Ave",
                            CompanyName = "Harvest Fresh",
                            Email = "emma@example.com",
                            FirstName = "Emma",
                            LastName = "Williams",
                            Password = "farmer4pass",
                            PhoneNumber = "555-1111",
                            TypeOfProduce = "Dairy",
                            Username = "harvest_fresh"
                        },
                        new
                        {
                            FarmerId = 5,
                            Address = "654 Meadow Rd",
                            CompanyName = "Silver Meadows",
                            Email = "daniel@example.com",
                            FirstName = "Daniel",
                            LastName = "Brown",
                            Password = "farmer5pass",
                            PhoneNumber = "555-2222",
                            TypeOfProduce = "Livestock",
                            Username = "silver_meadows"
                        },
                        new
                        {
                            FarmerId = 6,
                            Address = "987 Grain St",
                            CompanyName = "Pure Grains",
                            Email = "sophia@example.com",
                            FirstName = "Sophia",
                            LastName = "Garcia",
                            Password = "farmer6pass",
                            PhoneNumber = "555-3333",
                            TypeOfProduce = "Grains",
                            Username = "pure_grains"
                        },
                        new
                        {
                            FarmerId = 7,
                            Address = "741 Berry Lane",
                            CompanyName = "Blueberry Farm",
                            Email = "david@example.com",
                            FirstName = "David",
                            LastName = "Martinez",
                            Password = "farmer7pass",
                            PhoneNumber = "555-4444",
                            TypeOfProduce = "Berries",
                            Username = "blueberry_farm"
                        },
                        new
                        {
                            FarmerId = 8,
                            Address = "852 Harvest Rd",
                            CompanyName = "Organic Harvest",
                            Email = "olivia@example.com",
                            FirstName = "Olivia",
                            LastName = "Hernandez",
                            Password = "farmer8pass",
                            PhoneNumber = "555-5555",
                            TypeOfProduce = "Vegetables",
                            Username = "organic_harvest"
                        },
                        new
                        {
                            FarmerId = 9,
                            Address = "963 Pasture St",
                            CompanyName = "Pasture Perfect",
                            Email = "jacob@example.com",
                            FirstName = "Jacob",
                            LastName = "Lopez",
                            Password = "farmer9pass",
                            PhoneNumber = "555-6666",
                            TypeOfProduce = "Dairy",
                            Username = "pasture_perfect"
                        },
                        new
                        {
                            FarmerId = 10,
                            Address = "159 Leaf Rd",
                            CompanyName = "Green Leaf Farms",
                            Email = "ava@example.com",
                            FirstName = "Ava",
                            LastName = "Rodriguez",
                            Password = "farmer10pass",
                            PhoneNumber = "555-7777",
                            TypeOfProduce = "Herbs",
                            Username = "green_leaf"
                        });
                });

            modelBuilder.Entity("AgriEnergyConnect.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FarmerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            FarmerId = 1,
                            HarvestDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 4.99m,
                            ProductCode = "APL123",
                            ProductName = "Organic Apples"
                        },
                        new
                        {
                            ProductId = 2,
                            FarmerId = 3,
                            HarvestDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 3.00m,
                            ProductCode = "TOM789",
                            ProductName = "Fresh Tomatoes"
                        },
                        new
                        {
                            ProductId = 3,
                            FarmerId = 2,
                            HarvestDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 2.75m,
                            ProductCode = "CRN234",
                            ProductName = "Sweet Corn"
                        },
                        new
                        {
                            ProductId = 4,
                            FarmerId = 4,
                            HarvestDate = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 2.10m,
                            ProductCode = "CAR567",
                            ProductName = "Organic Carrots"
                        },
                        new
                        {
                            ProductId = 5,
                            FarmerId = 7,
                            HarvestDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 6.00m,
                            ProductCode = "STR789",
                            ProductName = "Fresh Strawberries"
                        },
                        new
                        {
                            ProductId = 6,
                            FarmerId = 7,
                            HarvestDate = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 7.00m,
                            ProductCode = "BLU567",
                            ProductName = "Blueberries"
                        },
                        new
                        {
                            ProductId = 7,
                            FarmerId = 3,
                            HarvestDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 3.50m,
                            ProductCode = "BPR321",
                            ProductName = "Bell Peppers"
                        },
                        new
                        {
                            ProductId = 8,
                            FarmerId = 2,
                            HarvestDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 2.50m,
                            ProductCode = "WHT456",
                            ProductName = "Golden Wheat"
                        },
                        new
                        {
                            ProductId = 9,
                            FarmerId = 6,
                            HarvestDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 3.20m,
                            ProductCode = "RCE987",
                            ProductName = "Brown Rice"
                        },
                        new
                        {
                            ProductId = 10,
                            FarmerId = 6,
                            HarvestDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 2.80m,
                            ProductCode = "BRL654",
                            ProductName = "Barley"
                        },
                        new
                        {
                            ProductId = 11,
                            FarmerId = 8,
                            HarvestDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 10.75m,
                            ProductCode = "CHA321",
                            ProductName = "Chia Seeds"
                        },
                        new
                        {
                            ProductId = 12,
                            FarmerId = 5,
                            HarvestDate = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 5.40m,
                            ProductCode = "SUN789",
                            ProductName = "Sunflower Seeds"
                        },
                        new
                        {
                            ProductId = 13,
                            FarmerId = 9,
                            HarvestDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 4.00m,
                            ProductCode = "MLK102",
                            ProductName = "Whole Milk"
                        },
                        new
                        {
                            ProductId = 14,
                            FarmerId = 9,
                            HarvestDate = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 8.99m,
                            ProductCode = "CHE221",
                            ProductName = "Cheddar Cheese"
                        },
                        new
                        {
                            ProductId = 15,
                            FarmerId = 4,
                            HarvestDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 6.00m,
                            ProductCode = "EGG321",
                            ProductName = "Free-Range Eggs"
                        },
                        new
                        {
                            ProductId = 16,
                            FarmerId = 5,
                            HarvestDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 10.50m,
                            ProductCode = "BEEF222",
                            ProductName = "Grass-Fed Beef"
                        },
                        new
                        {
                            ProductId = 17,
                            FarmerId = 5,
                            HarvestDate = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 8.75m,
                            ProductCode = "CHK333",
                            ProductName = "Pasture-Raised Chicken"
                        },
                        new
                        {
                            ProductId = 18,
                            FarmerId = 9,
                            HarvestDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 5.50m,
                            ProductCode = "GMLK777",
                            ProductName = "Organic Goat Milk"
                        },
                        new
                        {
                            ProductId = 19,
                            FarmerId = 10,
                            HarvestDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 12.99m,
                            ProductCode = "BSL555",
                            ProductName = "Fresh Basil"
                        },
                        new
                        {
                            ProductId = 20,
                            FarmerId = 10,
                            HarvestDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 14.00m,
                            ProductCode = "ROS444",
                            ProductName = "Rosemary"
                        },
                        new
                        {
                            ProductId = 21,
                            FarmerId = 6,
                            HarvestDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 15.50m,
                            ProductCode = "HNY999",
                            ProductName = "Fresh Honey"
                        },
                        new
                        {
                            ProductId = 22,
                            FarmerId = 5,
                            HarvestDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 11.25m,
                            ProductCode = "ALM555",
                            ProductName = "Almonds"
                        },
                        new
                        {
                            ProductId = 23,
                            FarmerId = 3,
                            HarvestDate = new DateTime(2025, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 2.50m,
                            ProductCode = "CUC303",
                            ProductName = "Cucumber"
                        },
                        new
                        {
                            ProductId = 24,
                            FarmerId = 1,
                            HarvestDate = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 5.99m,
                            ProductCode = "PIN202",
                            ProductName = "Pineapple"
                        },
                        new
                        {
                            ProductId = 25,
                            FarmerId = 4,
                            HarvestDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 4.75m,
                            ProductCode = "PMP808",
                            ProductName = "Pumpkin"
                        },
                        new
                        {
                            ProductId = 26,
                            FarmerId = 5,
                            HarvestDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 9.99m,
                            ProductCode = "WAL555",
                            ProductName = "Walnuts"
                        },
                        new
                        {
                            ProductId = 27,
                            FarmerId = 2,
                            HarvestDate = new DateTime(2025, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerKg = 3.25m,
                            ProductCode = "LET777",
                            ProductName = "Lettuce"
                        });
                });

            modelBuilder.Entity("AgriEnergyConnect.Models.Product", b =>
                {
                    b.HasOne("AgriEnergyConnect.Models.Farmer", null)
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
